### ISSUE TITLE
Getting more than one field to return information

### ISSUE THREAD

**Issue by ccdpowell** [bennylope/pygeocodio#7]
In playing around with this wrapper, I tried to pull all of the fields available when geocoding an address.  Heres my code:

r = '42370 Bob Hope Dr, Rancho Mirage CA'
geocoded_location = client.geocode(r, fields=['cd','school'] )

This returns the 'school' attribute of fields, but not the 'cd'.  I'd like to be able to pass more than one field and this doesn't not support this capability.

I would try to fix this myself, but I am not skilled enough in python.  

Thanks.

**Comment by bennylope** [comment]
Thanks for reporting this. Just got a fix for this as [version 0.4.1](https://pypi.python.org/pypi/pygeocodio)

**Comment by ccdpowell** [comment]
Thanks for hopping on this issue.  I just tried updating this and ran into a couple errors.  It looks like the allowed_domains check is failing.  See the attached screenshots.  You can see that fields is populated correctly, but wrapper is failing validation of fields on line 23.

Thanks again!

![screen shot 2015-02-17 at 4 50 01](https://cloud.githubusercontent.com/assets/2606927/6240630/f3a11f66-b6c5-11e4-88de-8568217da63a.png)

**Comment by ccdpowell** [comment]
NOTE:  I tried numerous other combinations including a list with one string and all fields separated by comma, and just a string of fields separated by comma.  All do not work.  Again, decorators are a little above my knowledge level, so I am getting lost in your code or else I would fix it myself.

**Comment by bennylope** [comment]
The `protect_fields` decorator is just wrapping the called function to validate anything passed in the `fields` keyword argument. If it validates, it returns the decorated function, if not - if one of the values in the list for the `fields` argument is not in the preapproved list of field names - then it raises the error instead.

The problem was that I had both `fields` flattening *and* kwarg validation in `geocode` and the related geocode methods. So when you call `geocode` the decorator checks that your fields are valid, then the `geocode` function flattened the fields, from a list like `["cd", "school"]` to a string, `"cd,school"`, which is sent as the value for the `fields` kwarg to the method that does the work - and since that method is decorated with the `protect_fields` decorator, it sees an invalid `fields` value.

You can download *this* update as version 0.4.2!

**Comment by snake-plissken** [comment]
Hi ccdpowell,

You have to pass in a list of the fields you want returned, like
geocode(address, fields = ['cd', 'school']).

On Tue, Feb 17, 2015 at 7:59 PM, ccdpowell <notifications@github.com> wrote:

> NOTE: I tried numerous other combinations including a list with one string
> and all fields separated by comma, and just a string of fields separated by
> comma. All do not work. Again, decorators are a little above my knowledge
> level, so I am getting lost in your code or else I would fix it myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bennylope/pygeocodio/issues/7#issuecomment-74790227>.
>



-- 


This message is intended only for the person to whom it is addressed. It
may contain confidential and privileged information. Should you receive
this message in error, kindly delete it from your computer and notify the
sender of the error in transmission. Thank you.

**Comment by bennylope** [comment]
And, yes, you do need to provide the list of fields you want to get back as a list of strings as @snake-plissken noted:
```python
geocode(address, fields = ['cd', 'school'])
```

**Comment by ccdpowell** [comment]
Thank you!  Works like a charm!
